### ISSUE TITLE
Error when dragging nodes out of view.

### ISSUE THREAD

**Issue by lukewarlow** [MrBlenny/react-flow-chart#135] opened 2020-04-29 14:35 UTC
In the latest release (https://github.com/MrBlenny/react-flow-chart/releases/tag/0.0.12) if a node is dragged "offscreen" an "Unable to find node on an unmounted component." is triggered.

This only occurs when the node is dragged offscreen, not when the canvas is dragged.
It can be reproduced on https://mrblenny.github.io/react-flow-chart/index.html?path=/story/sidebar--drag-and-drop by dragging the node behind the sidebar.

I've experienced this in my project as well as in the storybook. I've included a development stack trace below. Using version 0.0.11 I don't experience this issue.

Canvas scale is initialised to 1.

![image](https://user-images.githubusercontent.com/32498324/80608629-f7475f80-8a2e-11ea-94d5-5d0d0df6f1e2.png)

**Comment by georginaso** [comment] 2020-05-05 15:29
@lukewarlow if you're not using the zoom feature (and an external state), I guess that it will be solved initializing the chart state with the `scale` attribute to "1".

e.g. 
```{
  offset: {
    x: 0,
    y: 0,
  },
  scale: 1,
  nodes: {},
  links: {},
  selected: {},
  hovered: {},
}```

**Comment by georginaso** [comment] 2020-05-05 15:34
The real bug is "Error when dragging nodes out of view if scale not set to '1'".

Maybe the canvas is not resizing 🤔?

<img width="1680" alt="Screenshot 2020-05-05 at 17 32 40" src="https://user-images.githubusercontent.com/58181893/81084642-6ec93300-8ef6-11ea-931f-7beff8cd5b91.png">

**Comment by georginaso** [comment] 2020-05-05 15:36
You can reproduce this issue in the Storybook, setting a zoom in/out (easier to see with zoom out):
https://mrblenny.github.io/react-flow-chart/index.html?path=/story/other-config--zoom

**Comment by lukewarlow** [comment] 2020-05-05 16:12
I have this error with the chart scale set to 1. The rendering issue when zooming out is a separate issue.

**Comment by georginaso** [comment] 2020-05-05 17:35
OK @lukewarlow ! I will create a new one.  I thought that was the same because I have the same error --> "Unable to find node on an unmounted component."

**Comment by lukewarlow** [comment] 2020-05-05 18:35
@georginaso they're potentially linked. I tried debugging older commits to see when it was introduced but none of them would let me build the storybook.

**Comment by MrBlenny** [comment] 2020-05-09 06:06
I was getting the nodes not displaying but was not getting an error thrown. The display issue should be fixed here.
https://github.com/MrBlenny/react-flow-chart/commit/cc7f02f02fa0a18dad5d304189e02bea36ad6535

**Closed by MrBlenny** 2020-05-09 06:06 UTC

**Comment by lukewarlow** [comment] 2020-05-16 22:05
@MrBlenny this issue has not been fixed, this issue is related to dragging nodes out of view such as behind a sidebar.
